import os
import requests
from playwright.sync_api import sync_playwright

BOT_TOKEN = os.environ["BOT_TOKEN"]
CHAT_ID = os.environ["CHAT_ID"]

URL = "https://carro.mercadolivre.com.br/MLB-6864663498-ora-5-_JM"


def enviar_telegram(mensagem):
    requests.post(
        f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
        data={
            "chat_id": CHAT_ID,
            "text": mensagem
        }
    )


with sync_playwright() as p:
    navegador = p.chromium.launch(headless=True)

    pagina = navegador.new_page()

    try:
        pagina.goto(URL, timeout=60000)

        texto = pagina.text_content("body").lower()

        if (
            "comprar" not in texto
            and "reservar" not in texto
            and "tenho interesse" not in texto
        ):
            enviar_telegram(
                "🚨 Atenção!\n\n"
                "O anúncio do ORA 5 pode ter mudado de status.\n\n"
                f"{URL}"
            )

        else:
            print("Sem alterações.")

    except Exception as erro:
        print("Erro:", erro)

    navegador.close()
